name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  nodejs:
    name: Node.js
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [^12, ^14, ^16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --no-audit
      - run: npm test
